VARIAVEIS_POSSIVEIS = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
CARACTERE_SOMA = " + "
CARACTERE_SEPARAR = ","
CARACTERE_BARRAMENTO = "'"
CARACTERE_DIFERENTE = "_"
ESPACO = " "
BINARIO_0 = "0"
BINARIO_1 = "1"
BASE_BINARIA = 2
COMPARACOES_POR_VEZ = 2
RED   = "\033[1;31m"  
CYAN  = "\033[1;36m"
GREEN = "\033[0;32m"
RESET = "\033[0;0m"
YELLOW = "\033[1;33m"  